#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2
version:      0.24
version_from: Gtk2.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
