--- #YAML:1.0
name:                Gtk2
version:             1.200
abstract:            Perl interface to the 2.x series of the Gimp Toolkit library
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Cairo:                         1.000
    ExtUtils::Depends:             0.300
    ExtUtils::PkgConfig:           1.030
    Glib:                          1.200
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

configure_requires:
   ExtUtils::Depends: 0.300
   Glib: 1.200
   ExtUtils::PkgConfig: 1.030
   Cairo: 1.000
