#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2
version:      0.97
version_from: Gtk2.pm
installdirs:  site
requires:
     ExtUtils::Depends:         0.1
     Glib:                      1.00rc1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
