--- #YAML:1.0
name:               Gtk2
version:            1.201
abstract:           Perl interface to the 2.x series of the Gimp Toolkit library
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    Cairo:                1.000
    ExtUtils::Depends:    0.300
    ExtUtils::MakeMaker:  0
    ExtUtils::PkgConfig:  1.030
    Glib:                 1.200
requires:
    Cairo:                1.000
    ExtUtils::Depends:    0.300
    ExtUtils::PkgConfig:  1.030
    Glib:                 1.200
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
